White theme for transparent pages
YS-Wong/Adaptive-Tab-Bar-Color pull request #19
Opened 2022-06-29 08:59 UTC by omarcinkonis

If the element at the top is transparent, theme color should be set to white.

Before the update, transparent background would cause rgb(0, 0, 0) theme color (black), while the browser would render transparent background as white. This would create a mismatch between the page and browser theme. The problem was spotted on skelbiu.lt - the change may be tested there.

2022-06-29 22:21 UTC, YS-Wong requested changes
Good idea. But it seems that Firefox render transparent HTML background in color #ECECEC, or rgb(236, 236, 236), instead of pure white. I reckon `return { r: 236, g: 236, b: 236, a: 0}` might be better.

2022-06-30 00:15 UTC, YS-Wong approved these changes

2022-06-30 00:16 UTC, merged

2022-06-30 00:23 UTC, YS-Wong commented
Thanks for the participation! The change will be included in v1.6.1.

2022-06-30 10:20 UTC, omarcinkonis commented
I see that the update is now live. To me, there still is a mismatch on the website I originally mentioned. To test Firefox's behavior, I created a blank html file and Firefox renders it as pure white (#FFFFFF). Are you sure you aren't using any extensions that change the transparent color to off-white?

2022-06-30 13:39 UTC, YS-Wong commented
I think it has something to do with Firefox version. On Release version and Developer Edition, it renders as #ECECEC, but on Nightly it renders as #FFFFFF.

2022-06-30 16:38 UTC, YS-Wong commented
Also, I have seen your comment on the add-on market. Thanks for the 5-stars! I’ve received many suggestions to dim / lighten the tab bar a little. That feature is going to be added in short time.

2022-07-02 22:10 UTC, omarcinkonis commented
Awesome. Another feature I would like to see is an input + button to save a default color for the current website. I looked into it a little, but it seems that custom colors aren't implemented yet (it's impossible to save them in the settings). I don't have experience with add-ons, so it takes time for me to figure less obvious things out, but I might try looking into it more, once I have a little more free time.